---
plugin: networktocode.nautobot.gql_inventory
validate_certs: false

query:
  devices:
    tags: name
    serial:
    tenant: name
    status: display
    role: name
    location:
      name:
      parent: name
    platform:
      napalm_driver:
      name:
      network_driver:
    interfaces:
      name:
      ip_addresses:
        address:
  virtual_machines:
    tags: name
    tenant: name
    status: display

group_by:
  - location.name
  - status.display
  - role.name
