---
# IPAM-focused rulebook - reacts to IP address changes and triggers AAP job templates
- name: React to Nautobot IP Address changes
  hosts: all
  sources:
    - networktocode.nautobot.nautobot_changelog:
        instance: "{{ NAUTOBOT_URL }}"
        token: "{{ NAUTOBOT_TOKEN }}"
        interval: 5
  rules:
    # Rule 1: New IP address created
    - name: IP address created - configure on device
      condition: >
        event.host is defined
        and event.ip_version is defined
        and event.created is defined
      action:
        run_job_template:
          name: "Configure IP on Arista"
          organization: "Default"
          extra_vars:
            ip_address: "{{ event.host }}"
            mask_length: "{{ event.mask_length }}"
            ip_version: "{{ event.ip_version }}"
            parent_prefix: "{{ event.parent }}"
            status: "{{ event.status }}"
            dns_name: "{{ event.dns_name }}"
            description: "{{ event.description }}"
            role: "{{ event.role }}"
            timestamp: "{{ event.created }}"

    # Rule 2: IP address updated
    - name: IP address updated - run compliance check
      condition: >
        event.host is defined
        and event.last_updated is defined
        and event.last_updated != event.created
      action:
        run_job_template:
          name: "IPAM - IP Address Compliance Check"
          organization: "Default"
          extra_vars:
            ip_address: "{{ event.host }}/{{ event.mask_length }}"
            ip_version: "{{ event.ip_version }}"
            status: "{{ event.status }}"
            last_updated: "{{ event.last_updated }}"
